name: distro component test

on:
  pull_request:
    branches: [ main ]

env:
  GO_VERSION: 1.22.x

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: test components
        run: find . -name go.mod -execdir go test -v ./... \;

